// Questions Fetch
export const QUESTIONS_FETCH_REQUEST = "QUESTIONS_FETCH_REQUEST";
export const QUESTIONS_FETCH_SUCCESS = "QUESTIONS_FETCH_SUCCESS";
export const QUESTIONS_FETCH_ERROR = "QUESTIONS_FETCH_ERROR";
export const QUESTIONS_FETCH_RESET = "QUESTIONS_FETCH_RESET";

// Question Create
export const QUESTION_CREATE_REQUEST = "QUESTION_CREATE_REQUEST";
export const QUESTION_CREATE_SUCCESS = "QUESTION_CREATE_SUCCESS";
export const QUESTION_CREATE_ERROR = "QUESTION_CREATE_ERROR";
export const QUESTION_CREATE_RESET = "QUESTION_CREATE_RESET";

// Question Update
export const QUESTION_UPDATE_REQUEST = "QUESTION_UPDATE_REQUEST";
export const QUESTION_UPDATE_SUCCESS = "QUESTION_UPDATE_SUCCESS";
export const QUESTION_UPDATE_ERROR = "QUESTION_UPDATE_ERROR";
export const QUESTION_UPDATE_RESET = "QUESTION_UPDATE_RESET";

// Question Delete
export const QUESTION_DELETE_REQUEST = "QUESTION_DELETE_REQUEST";
export const QUESTION_DELETE_SUCCESS = "QUESTION_DELETE_SUCCESS";
export const QUESTION_DELETE_ERROR = "QUESTION_DELETE_ERROR";
export const QUESTION_DELETE_RESET = "QUESTION_DELETE_RESET";
